mount_point = "/mnt/verfs/"
data_dir = "/mnt/work/verfs/"
sync_interval_ms = 5000
batch_max_blocks = 3000
batch_flush_interval_ms = 500
metadata_cache_capacity_entries = 131072
chunk_cache_capacity_entries = 262144
pack_index_cache_capacity_entries = 524288
zstd_compression_level = 3
ultracdc_min_size_bytes = 2048
ultracdc_avg_size_bytes = 4096
ultracdc_max_size_bytes = 16384
fuse_max_write_bytes = 1048576
gc_idle_min_ms = 15000
gc_pack_rewrite_min_reclaim_bytes = 67108864
gc_pack_rewrite_min_reclaim_percent = 25.0
gc_discard_filename = ".DISCARD"
vault_enabled = true
vault_argon2_mem_kib = 131072
vault_argon2_iters = 3
vault_argon2_parallelism = 1
